export const invokeTrackEvent = (eventName, payload = {}) => {
  if (window.webengage) webengage?.track(eventName, payload);
};

// export const trackEventDefaultOptions = Object.freeze({
//   "Top Menu Icon Clicked": {
//     event: "customevent",
//     eventName: "Top Menu Icon Clicked",
//     eventCategory: "homepage",
//     eventAction: "banner swipe",
//     eventLabel: "right or left",
//   },
// });

export const EVENT_NAMES = {
  SESSION_STARTED: "Session_started",
  APP_INSTALLED: "App_Installed",
  APP_UNINSTALLED: "App_Uninstalled",
  PAGE_VIEWED: "Page Viewed",
  TOP_MENU_ICON_CLICKED: "Top Menu Icon Clicked",
  CATEGORY_CLICKED: "Category Clicked",
  EXPLORE_NOW_CLICKED: "Explore Now Clicked",
  FUND_YOUR_WALLET_CLICKED: "Fund Your Wallet Clicked",
  NFT_CLICKED: "NFT Clicked",
  NFT_VIEWED: "NFT Viewed",
  MCL_SCHEDULE_CLICKED: "MCL Schedule Clicked",
  CRICKET_NFT_CHECKED: "Cricket NFT Checked",
  NFT_ADDED_TO_WISHLIST: "NFT Added to Wishlist",
  SOCIAL_MEDIA_ICON_CLICKED: "Social Media Icon Clicked",
  VIDEO_PLAYED: "Video Played",
  ABOUT_US_CLICKED: "About Us Clicked",
  FAQS_CLICKED: "FAQs Clicked",
  BLOG_CLICKED: "Blog Clicked",
  CONTACT_US_CLICKED: "Contact Us Clicked",
  ABOUTS_US_FORM_SUBMITTED: "Abouts Us Form Submitted",
  NFTS_ON_RENT_VIEWED: "NFTs on Rent Viewed",
  ADDED_TO_CART: "Added to Cart",
  BUY_NOW_CLICKED: "Buy Now Clicked",
  VERIFY_KYC_CLICKED: "Verify KYC Clicked",
  GUARDIANLINK_WALLET_VIEWED: "GuardianLink Wallet Viewed",
  GUARDIANLINK_WALLET_DEPOSITED_INITIATED:
    "GuardianLink Wallet Deposited Initiated",
  GUARDIANLINK_WALLET_DEPOSITED_COMPLETED:
    "GuardianLink Wallet Deposited Completed",
  GUARDIANLINK_WALLET_WITHDRAWED: "GuardianLink Wallet Withdrawed",
  ORDER_CLICKED: "Order Clicked",
  PROFILE_UPDATED: "Profile Updated",
  BORROW_NFT_CLICKED: "Borrow NFT Clicked",
  MY_ORDERS_TRANSFERRED_VIEWED: "My Orders - Transferred Viewed",
  MY_ORDERS_PENDING_VIEWED: "My Orders - Pending Viewed",
  MY_ORDERS_EXPIRED_VIEWED: "My Orders - Expired Viewed",
  ORDER_DETAILS_CHECKED: "Order Details Checked",
  INVOICES_BUY_ORDERS_CHECKED: "Invoices - Buy Orders Checked",
  INVOICES_SELL_ORDERS_CHECKED: "Invoices - Sell Orders Checked",
  DOWNLOAD_INVOICE: "Download Invoice",
  MY_BIDS_ACTIVE_BIDS: "My Bids - Active Bids",
  MY_BIDS_OUT_BIDS: "My Bids - Out Bids",
  BID_PLACED: "Bid Placed",
  CART_VIEWED: "Cart Viewed",
  REMOVED_FROM_CART: "Removed from Cart",
  KYC_STARTED: "KYC Started",
  KYC_COMPLETED: "KYC Completed",
  FILTER_APPLIED: "Filter Applied",
  RENTAL_FILTER_APPLIED: "Rental Filter Applied",
  FILTER_REMOVED: "Filter Removed",
  CHECKOUT_STARTED: "Checkout Started",
  CHECKOUT_COMPLETED: "Checkout Completed",
  BID_CHECKOUT_STARTED: "Bid Checkout Started",
  BID_CHECKOUT_ENDED: "Bid Checkout Ended",
};

export const PAGES = {
  "": "home-page",
  "/": "home-page",
  "/about-us": "about-us-page",
  "/announcment/[slug]": "",
  "/announcment-list": "",
  "/blog": "",
  "/call-it": "call-it",
  "/bmw-contest-terms-and-conditions": "",
  "/creator-application": "",
  "/details/[slug]": "details-page",
  "/drop/crypto-bat-nfts": "crypto-bat-page",
  "/drop/mcl-shot-nfts": "mcl-shots-page",
  "/drop/one-dollar-nfts": "one-dollar-page",
  "/drop/raddx-car-nfts": "raddx-page",
  "/drop/free-mcl-pass": "mcl-pass-page",
  "/drop/mcl-fusor-nfts": "mcl-fusor-nfts",
  "/faq": "faq-page",
  "/mcl-game": "mcl-game-page",
  "/kyc": "kyc-page",
  "/nft-marketplace/[category]": "",
  "/nft-marketplace/mcl": "mcl-marketplace-page",
  "/nft-marketplace/raddx": "raddx-marketplace-page",
  "/nft-marketplace/contest": "",
  "/nft-marketplace": "marketplace-page",
  "/nft-marketplace/cricket-nfts/[player]": "player-page",
  "/nft-marketplace/cricket-nfts/[player]/details/[slug]":
    "player-details-page",
  "/nft-marketplace/cricket-nfts/[player]/order/details/[slug]/[orderslug]":
    "player-order-details-page",
  "/nft-marketplace/details/[slug]": "nft-details-page",
  "/nft-marketplace/favorites": "favorites-page",
  "/nft-marketplace/live-auction": "live-auction-page",
  "/nft-marketplace/sale-history": "sale-history-page",
  "/nft-marketplace/trending-nfts": "trending-page",
  "/nft-rental": "rental-page",
  "/offers": "offers-page",
  "/order/details/[slug]/[orderSlug]": "order-details-page",
  "/privacy-policy": "privacy-policy-page",
  "/referral-program": "referral-program-page",
  "/release-notes": "release-notes-page",
  "/spin-wheel-of-fortune": "spin",
  "/spin-wheel-contest-terms-and-conditions": "spin-wheel t&c",
  "/terms-and-conditions": "t&c Page",
  "/user/[slug]/details": "user-details-page",
};
